# Generated by Django 4.2.4 on 2023-08-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_category_photo_dish_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='defaults/default-image.jpg', upload_to='photos/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
